# Generated by Django 6.0.7 on 2026-07-20 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hoapital',
            new_name='Hospital',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='is_open',
            new_name='is_open_24_7',
        ),
    ]
