# Generated by Django 6.0.7 on 2026-07-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_rename_hoapital_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='description',
        ),
    ]
