# Generated by Django 6.0.6 on 2026-07-25 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_patient_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='hoapital',
            new_name='hospital',
        ),
    ]
