# Generated by Django 6.0.7 on 2026-08-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_doctor_hospital_alter_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consulation_fee',
            new_name='consultation_fee',
        ),
    ]
