# Generated by Django 6.0.6 on 2026-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_appointment_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='icon',
            field=models.CharField(blank=True, default='fa-notes-medical', max_length=50),
        ),
    ]
