# Generated by Django 6.0.6 on 2026-08-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_speciality_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
