# Generated by Django 6.0.6 on 2026-08-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_speciality_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
