# Generated by Django 6.0.6 on 2026-08-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_hospital_photo_alter_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='afternoon_hours',
            field=models.CharField(blank=True, help_text='e.g. 3:00 PM - 6:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.CharField(blank=True, help_text='e.g. Saturday, Sunday, Tuesday, Thursday', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='evening_hours',
            field=models.CharField(blank=True, help_text='e.g. 7:00 PM - 10:00 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='morning_hours',
            field=models.CharField(blank=True, help_text='e.g. 9:00 AM - 12:00 PM', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=100),
        ),
    ]
