# Generated by Django 6.0.6 on 2026-08-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_doctor_afternoon_hours_doctor_available_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_today',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='next_available',
        ),
    ]
