# Generated by Django 6.0.7 on 2026-08-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_remove_doctor_available_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Prof. Dr.', 'Prof. Dr.'), ('Asst. Prof. Dr.', 'Asst. Prof. Dr.'), ('Assoc. Prof. Dr.', 'Assoc. Prof. Dr.')], default='Dr.', max_length=30),
        ),
    ]
