# Generated by Django 6.0.6 on 2026-08-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_doctor_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Nutrition', 'Nutrition'), ('Fitness', 'Fitness'), ('Mental Health', 'Mental Health'), ('Sleep', 'Sleep'), ('Wellness', 'Wellness'), ('Heart Health', 'Heart Health')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('short_description', models.CharField(help_text='Shown on the card', max_length=300)),
                ('content', models.TextField(help_text='Full blog content, shown on detail page')),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
